const zodiacs = [
  {
    id: '1',
    name: 'aquarius',
    dates: 'Jan 21 - Feb 19',
    symbol: 'Water Bearer',
    // horoscope: 'https://www.laughsend.com/horoscopes/aquarius.php',
  },
  {
    id: '2',
    name: 'aries',
    dates: 'Mar 21 - Apr 19',
    symbol: 'Ram',
    // horoscope: 'https://www.laughsend.com/horoscopes/aries.php',
  },
  {
    id: '3',
    name: 'cancer',
    dates: 'Jun 21 - Jul 22',
    symbol: 'Crab',
    // horoscope: 'https://www.laughsend.com/horoscopes/cancer.php',
  },
  {
    id: '4',
    name: 'capricorn',
    dates: 'Dec 22 - Feb 19',
    symbol: 'Goat',
    // horoscope: 'https://www.laughsend.com/horoscopes/capricorn.php',
  },
  {
    id: '5',
    name: 'gemini',
    dates: 'May 21 - Jun 20',
    symbol: 'Twins',
    // horoscope: 'https://www.laughsend.com/horoscopes/gemini.php',
  },
  {
    id: '6',
    name: 'leo',
    dates: 'Jul 23 - Aug 22',
    symbol: 'Lion',
    // horoscope: 'https://www.laughsend.com/horoscopes/leo.php',
  },
  {
    id: '7',
    name: 'libra',
    dates: 'Sept 23 - Oct 22',
    symbol: 'Balance',
    // horoscope: 'https://www.laughsend.com/horoscopes/libra.php',
  },
  {
    id: '8',
    name: 'pisces',
    dates: 'Feb 19 - Mar 20',
    symbol: 'Fish',
    // horoscope: 'https://www.laughsend.com/horoscopes/pisces.php',
  },
  {
    id: '9',
    name: 'sagittarius',
    dates: 'Nov 22 - Dec 21',
    symbol: 'Archer',
    // horoscope: 'https://www.laughsend.com/horoscopes/sagittarius.php',
  },
  {
    id: '10',
    name: 'scorpio',
    dates: 'Oct 23 - Nov 21',
    symbol: 'Scorpion',
    // horoscope: 'https://www.laughsend.com/horoscopes/scorpio.php',
  },
  {
    id: '11',
    name: 'taurus',
    dates: 'Apr 20 - May 20',
    symbol: 'Bull',
    // horoscope: 'https://www.laughsend.com/horoscopes/taurus.php',
  },
  {
    id: '12',
    name: 'virgo',
    dates: 'Aug 23 - Sep 22',
    symbol: 'Virgin',
    // horoscope: 'https://www.laughsend.com/horoscopes/virgo.php',
  },
];

module.exports = { zodiacs };
